version: "3.1"

services:
  db:
    image: postgres:16-alpine
    container_name: proyecto-musical-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-musical_password}
      POSTGRES_USER: ${DB_USER:-musical_user}
      POSTGRES_DB: ${DB_NAME:-musical_db}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - musical_pg_data:/var/lib/postgresql/data

volumes:
  musical_pg_data:
